joint0_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint0
    joint_speed: 1.17
    motor:
        id: 10
        init: 512
        min: 0
        max: 1023

joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 1.17
    motor:
        id: 11
        init: 512
        min: 0
        max: 1023

joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 1.17
    motor:
        id: 12
        init: 512
        min: 0
        max: 1023


joint3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint3
    joint_speed: 1.17
    motor:
        id: 13
        init: 512
        min: 0
        max: 1023

joint4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint4
    joint_speed: 1.17
    motor:
        id: 14
        init: 512
        min: 0
        max: 1023
